repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer


-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args:
          - --py3-plus
          - --unclassifiable-application-module=tests


-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
        args:
          - --max-line-length=120
          - --ignore=E252 


-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D100,D213,D407,D406

- repo: https://github.com/nbqa-dev/nbqa
  rev: 1.2.2
  hooks:
    - id: nbqa-pydocstyle
    - id: nbqa-flake8
      args:
        - --max-line-length=88
    - id: nbqa-isort
    - id: nbqa-autopep8